### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by hazed59** [MatthewGammon/Conflict-Regear#2]
how long until this works?

**Comment by MatthewGammon** [comment]
> how long until this works?

This project will probably never have full functionality. 
I started it as a hobby project during my coding bootcamp and I'm working on it just to continue practicing with React. 
My old guild had a more archaic regear system and I thought this could potentially be an improvement, but it presents a number of challenges I'm not sure how to best resolve. 

We currently have our regears through a Discord bot which takes care of the authentication and authorization aspects without burdening guild members with logging into another platform. 

I'll still be plugging away at this, but progress will be slow and it won't be polished for a long time.

**Comment by hazed59** [comment]
any chance u could share the discord bot that yall use for regears?

**Comment by MatthewGammon** [comment]
> any chance u could share the discord bot that yall use for regears?

I wish I could, but I have not been able to talk to the creator other than to confirm that he was the one who made it. 
I don't know if it's for public use or internal guild use only. I also don't know where the repo is located or if it is public. 

What system are you currently using for regears?

**Comment by hazed59** [comment]
having to do it manually which is a pain

**Comment by MatthewGammon** [comment]
> having to do it manually which is a pain

Hey, I see you found a discord bot. Were you able to get it set up to handle your regears?

**Comment by hazed59** [comment]
No

**Comment by MatthewGammon** [comment]
> 

The front end still needs a little work, but right now I am getting the backend setup to be able to handle regear POST requests. 
If you want to shoot me an email we could discuss your guild's regear requirements. Min IP, gear equivalent, what pieces are regeared, etc so that I can get it set up. No promises on anything, but I could definitely give it a go if you are interested. 

matthewgammondev@gmail.com
